// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Combination struct {
	Combinations int `json:"combinations"`
}

type Mutation struct {
}

type Query struct {
}

type Score struct {
	Value string `json:"value"`
}
